AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
  - 'db/schema.rb'

require:
  - rubocop-rspec
  - rubocop-performance

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
