AllCops:
  TargetRubyVersion: 2.6.6
  NewCops: enable
  Exclude:
  - 'db/schema.rb'

require:
  - rubocop-rspec
  - rubocop-performance

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false
